---
title: "Chess Tournament Data"
subtitle: "Project 1: Approach"
author: "Jocelyn Slater"
format: html
editor: visual
---

```{r load-packages, message=FALSE, echo=FALSE}
library(tidyverse)
library(readr)
library(data.table)
library(ggplot2)
```

## Task

In this project, you’re given a text file with chess tournament results where the information has some structure. Your job is to create an R Markdown file that generates a .CSV file (that could for example be imported into a SQL database) with the following information for all of the players:
  - Player’s Name
  - Player’s State
  - Total Number of Points
  - Player’s Pre-Rating
  - Average Pre Chess Rating of Opponents
  
For the first player, the information would be:
Gary Hua, ON, 6.0, 1794, 1605

1605 was calculated by using the pre-tournament opponents’ ratings of 1436, 1563, 1600, 1610, 1649, 1663, 1716, and dividing by the total number of games played.

If you have questions about the meaning of the data or the results, please post them on the discussion forum. Data science, like chess, is a game of back and forth… The chess rating system (invented by a Minnesota statistician named Arpad Elo) has been used in many other contexts, including assessing relative strength of employment candidates by human resource departments.You may substitute another text file (or set of text files, or data scraped from web pages) of similar or greater complexity, and create your own assignment and solution. You may work in a small team. All of your code should be in an R markdown file (and published to rpubs.com); with your data accessible for the person running the script.

## Outline

-   Read in text file
-   Parse text to extract a dataframe of information with the following columns
    - Pair
    - Num
    - Player Name     
    - USCF ID 
    - Pre Rating (omit provisional information)
    - Post Rating
    - Total Points
    - Round 1
      - Check to see if it is a Win, Loss, or Draw - if not, ignore
    - Round 2
    - ...
    - Round 7 
- For each row, calculate the Average Pre Chess Rating of Opponents
  - Look up players by player number, get their pre-rating, and take the average
  - Save this as another column
- For each row (player), print information to .csv file
  - Player’s Name - Player’s State - Total Number of Points - Player’s Pre-Rating - Average Pre Chess Rating of Opponents
  

## Anticipated Challenges

- I have limited experience using conditional statements in R, some learning curve there
- No prior knowledge of Chess rating systems
- No prior experience writing text files
- Limited experience parsing text files to create dataframes

## Submission Requirements

-   Post all code (SQL, R, Quarto) in a GitHub repository

-   Submit the GitHub link

-   RPubs publication
